// Spell Data Service
// Provides spell list and search functionality for character spell selection

// Spell data: name, level (0 = cantrip), school, castingTime, range, duration, components, concentration, ritual
const SPELLS = [
    { name: "Acid Splash", level: 0, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Aid", level: 2, school: "Abjuration", castingTime: "Action", range: "30 ft", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Alarm", level: 1, school: "Abjuration", castingTime: "1 minute", range: "30 ft", duration: "8 hours", components: "V,S,M", concentration: false, ritual: true },
    { name: "Alter Self", level: 2, school: "Transmutation", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Animal Friendship", level: 1, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Animal Messenger", level: 2, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: true },
    { name: "Animal Shapes", level: 8, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "24 hours", components: "V,S", concentration: false, ritual: false },
    { name: "Animate Dead", level: 3, school: "Necromancy", castingTime: "1 minute", range: "10 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Animate Objects", level: 5, school: "Transmutation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Antilife Shell", level: 5, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Antimagic Field", level: 8, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Antipathy/Sympathy", level: 8, school: "Enchantment", castingTime: "1 hour", range: "60 ft", duration: "10 days", components: "V,S,M", concentration: false, ritual: false },
    { name: "Arcane Eye", level: 4, school: "Divination", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Arcane Gate", level: 6, school: "Conjuration", castingTime: "Action", range: "500 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Arcane Lock", level: 2, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Arcane Vigor", level: 2, school: "Abjuration", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Armor of Agathys", level: 1, school: "Abjuration", castingTime: "Bonus Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Arms of Hadar", level: 1, school: "Conjuration", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Astral Projection", level: 9, school: "Necromancy", castingTime: "1 hour", range: "10 ft", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Augury", level: 2, school: "Divination", castingTime: "1 minute", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: true },
    { name: "Aura of Life", level: 4, school: "Abjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V", concentration: true, ritual: false },
    { name: "Aura of Purity", level: 4, school: "Abjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V", concentration: true, ritual: false },
    { name: "Aura of Vitality", level: 3, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Awaken", level: 5, school: "Transmutation", castingTime: "8 hours", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Bane", level: 1, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Banishing Smite", level: 5, school: "Conjuration", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Banishment", level: 4, school: "Abjuration", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Barkskin", level: 2, school: "Transmutation", castingTime: "Bonus Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Beacon of Hope", level: 3, school: "Abjuration", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Beast Sense", level: 2, school: "Divination", castingTime: "Action", range: "Touch", duration: "1 hour", components: "S", concentration: true, ritual: true },
    { name: "Befuddlement", level: 8, school: "Enchantment", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Bestow Curse", level: 3, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Bigby's Hand", level: 5, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Blade Barrier", level: 6, school: "Evocation", castingTime: "Action", range: "90 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Blade of Disaster", level: 9, school: "Conjuration", castingTime: "Bonus Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Blade Ward", level: 0, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Bless", level: 1, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Blight", level: 4, school: "Necromancy", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Blinding Smite", level: 3, school: "Evocation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: false, ritual: false },
    { name: "Blindness/Deafness", level: 2, school: "Transmutation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V", concentration: false, ritual: false },
    { name: "Blink", level: 3, school: "Transmutation", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: false, ritual: false },
    { name: "Blur", level: 2, school: "Illusion", castingTime: "Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Burning Hands", level: 1, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Call Lightning", level: 3, school: "Conjuration", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Calm Emotions", level: 2, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Chain Lightning", level: 6, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Charm Monster", level: 4, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Charm Person", level: 1, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Chill Touch", level: 0, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Chromatic Orb", level: 1, school: "Evocation", castingTime: "Action", range: "90 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Circle of Death", level: 6, school: "Necromancy", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Circle of Power", level: 5, school: "Abjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V", concentration: true, ritual: false },
    { name: "Clairvoyance", level: 3, school: "Divination", castingTime: "10 minutes", range: "1 mile", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Clone", level: 8, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Cloud of Daggers", level: 2, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Cloudkill", level: 5, school: "Conjuration", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Color Spray", level: 1, school: "Illusion", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Command", level: 1, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Commune", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "1 minute", components: "V,S,M", concentration: false, ritual: true },
    { name: "Commune with Nature", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: true },
    { name: "Compelled Duel", level: 1, school: "Enchantment", castingTime: "Bonus Action", range: "30 ft", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Comprehend Languages", level: 1, school: "Divination", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Compulsion", level: 4, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Cone of Cold", level: 5, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Confusion", level: 4, school: "Enchantment", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Conjure Animals", level: 3, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Conjure Barrage", level: 3, school: "Conjuration", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Conjure Celestial", level: 7, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Conjure Elemental", level: 5, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Conjure Fey", level: 6, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Conjure Minor Elementals", level: 4, school: "Conjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Conjure Volley", level: 5, school: "Conjuration", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Conjure Woodland Beings", level: 4, school: "Conjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Contact Other Plane", level: 5, school: "Divination", castingTime: "1 minute", range: "Self", duration: "1 minute", components: "V", concentration: false, ritual: true },
    { name: "Contagion", level: 5, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "7 days", components: "V,S", concentration: false, ritual: false },
    { name: "Contingency", level: 6, school: "Abjuration", castingTime: "10 minutes", range: "Self", duration: "10 days", components: "V,S,M", concentration: false, ritual: false },
    { name: "Continual Flame", level: 2, school: "Evocation", castingTime: "Action", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Control Water", level: 4, school: "Transmutation", castingTime: "Action", range: "300 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Control Weather", level: 8, school: "Transmutation", castingTime: "10 minutes", range: "Self", duration: "8 hours", components: "V,S,M", concentration: true, ritual: false },
    { name: "Cordon of Arrows", level: 2, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Counterspell", level: 3, school: "Abjuration", castingTime: "Reaction", range: "60 ft", duration: "Instantaneous", components: "S", concentration: false, ritual: false },
    { name: "Create Food and Water", level: 3, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Create or Destroy Water", level: 1, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Create Undead", level: 6, school: "Necromancy", castingTime: "1 minute", range: "10 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Creation", level: 5, school: "Illusion", castingTime: "1 minute", range: "30 ft", duration: "Special", components: "V,S,M", concentration: false, ritual: false },
    { name: "Crown of Madness", level: 2, school: "Enchantment", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Crusader's Mantle", level: 3, school: "Evocation", castingTime: "Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Cure Wounds", level: 1, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Dancing Lights", level: 0, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Darkness", level: 2, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,M", concentration: true, ritual: false },
    { name: "Darkvision", level: 2, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Daylight", level: 3, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Death Ward", level: 4, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S", concentration: false, ritual: false },
    { name: "Delayed Blast Fireball", level: 7, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Demiplane", level: 8, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "S", concentration: false, ritual: false },
    { name: "Destructive Wave", level: 5, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Detect Evil and Good", level: 1, school: "Divination", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Detect Magic", level: 1, school: "Divination", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: true },
    { name: "Detect Poison and Disease", level: 1, school: "Divination", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: true },
    { name: "Detect Thoughts", level: 2, school: "Divination", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Dimension Door", level: 4, school: "Conjuration", castingTime: "Action", range: "500 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Disguise Self", level: 1, school: "Illusion", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Disintegrate", level: 6, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Dispel Evil and Good", level: 5, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Dispel Magic", level: 3, school: "Abjuration", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Dissonant Whispers", level: 1, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Divination", level: 4, school: "Divination", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: true },
    { name: "Divine Favor", level: 1, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V,S", concentration: false, ritual: false },
    { name: "Divine Smite", level: 1, school: "Evocation", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Divine Word", level: 7, school: "Evocation", castingTime: "Bonus Action", range: "30 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Dominate Beast", level: 4, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Dominate Monster", level: 8, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Dominate Person", level: 5, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Dragon's Breath", level: 2, school: "Transmutation", castingTime: "Bonus Action", range: "Touch", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Drawmij's Instant Summons", level: 6, school: "Conjuration", castingTime: "1 minute", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: true },
    { name: "Dream", level: 5, school: "Illusion", castingTime: "1 minute", range: "Special", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Druidcraft", level: 0, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Earthquake", level: 8, school: "Transmutation", castingTime: "Action", range: "500 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Eldritch Blast", level: 0, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Elemental Weapon", level: 3, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Elementalism", level: 0, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Enhance Ability", level: 2, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Enlarge/Reduce", level: 2, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Ensnaring Strike", level: 1, school: "Conjuration", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Entangle", level: 1, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Enthrall", level: 2, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Etherealness", level: 7, school: "Conjuration", castingTime: "Action", range: "Self", duration: "8 hours", components: "V,S", concentration: false, ritual: false },
    { name: "Evard's Black Tentacles", level: 4, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Expeditious Retreat", level: 1, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Eyebite", level: 6, school: "Necromancy", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Fabricate", level: 4, school: "Transmutation", castingTime: "10 minutes", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Faerie Fire", level: 1, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "False Life", level: 1, school: "Necromancy", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Fear", level: 3, school: "Illusion", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Feather Fall", level: 1, school: "Transmutation", castingTime: "Reaction", range: "60 ft", duration: "1 minute", components: "V,M", concentration: false, ritual: false },
    { name: "Feign Death", level: 3, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Find Familiar", level: 1, school: "Conjuration", castingTime: "1 hour", range: "10 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: true },
    { name: "Find Steed", level: 2, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Find the Path", level: 6, school: "Divination", castingTime: "1 minute", range: "Self", duration: "1 day", components: "V,S,M", concentration: true, ritual: false },
    { name: "Find Traps", level: 2, school: "Divination", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Finger of Death", level: 7, school: "Necromancy", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Fire Bolt", level: 0, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Fire Shield", level: 4, school: "Evocation", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: false, ritual: false },
    { name: "Fire Storm", level: 7, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Fireball", level: 3, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Flame Blade", level: 2, school: "Evocation", castingTime: "Bonus Action", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Flame Strike", level: 5, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Flaming Sphere", level: 2, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Flesh to Stone", level: 6, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Fly", level: 3, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Fog Cloud", level: 1, school: "Conjuration", castingTime: "Action", range: "120 ft", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Forbiddance", level: 6, school: "Abjuration", castingTime: "10 minutes", range: "Touch", duration: "1 day", components: "V,S,M", concentration: false, ritual: true },
    { name: "Forcecage", level: 7, school: "Evocation", castingTime: "Action", range: "100 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Foresight", level: 9, school: "Divination", castingTime: "1 minute", range: "Touch", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Fount of Moonlight", level: 4, school: "Evocation", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Freedom of Movement", level: 4, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Friends", level: 0, school: "Enchantment", castingTime: "Action", range: "10 ft", duration: "1 minute", components: "S,M", concentration: true, ritual: false },
    { name: "Gaseous Form", level: 3, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Gate", level: 9, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Geas", level: 5, school: "Enchantment", castingTime: "1 minute", range: "60 ft", duration: "30 days", components: "V", concentration: false, ritual: false },
    { name: "Gentle Repose", level: 2, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "10 days", components: "V,S,M", concentration: false, ritual: true },
    { name: "Giant Insect", level: 4, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Glibness", level: 8, school: "Enchantment", castingTime: "Action", range: "Self", duration: "1 hour", components: "V", concentration: false, ritual: false },
    { name: "Globe of Invulnerability", level: 6, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Glyph of Warding", level: 3, school: "Abjuration", castingTime: "1 hour", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Goodberry", level: 1, school: "Conjuration", castingTime: "Action", range: "Self", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Grasping Vine", level: 4, school: "Conjuration", castingTime: "Bonus Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Grease", level: 1, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: false, ritual: false },
    { name: "Greater Invisibility", level: 4, school: "Illusion", castingTime: "Action", range: "Touch", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Greater Restoration", level: 5, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Guardian of Faith", level: 4, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "8 hours", components: "V", concentration: false, ritual: false },
    { name: "Guards and Wards", level: 6, school: "Abjuration", castingTime: "1 hour", range: "Touch", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Guidance", level: 0, school: "Divination", castingTime: "Action", range: "Touch", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Guiding Bolt", level: 1, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "1 round", components: "V,S", concentration: false, ritual: false },
    { name: "Gust of Wind", level: 2, school: "Evocation", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hail of Thorns", level: 1, school: "Conjuration", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Hallow", level: 5, school: "Abjuration", castingTime: "24 hours", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Hallucinatory Terrain", level: 4, school: "Illusion", castingTime: "10 minutes", range: "300 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Harm", level: 6, school: "Necromancy", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Haste", level: 3, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Heal", level: 6, school: "Abjuration", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Healing Word", level: 1, school: "Abjuration", castingTime: "Bonus Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Heat Metal", level: 2, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hellish Rebuke", level: 1, school: "Evocation", castingTime: "Reaction", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Heroes' Feast", level: 6, school: "Conjuration", castingTime: "10 minutes", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Heroism", level: 1, school: "Enchantment", castingTime: "Action", range: "Touch", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Hex", level: 1, school: "Enchantment", castingTime: "Bonus Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hold Monster", level: 5, school: "Enchantment", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hold Person", level: 2, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Holy Aura", level: 8, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hunger of Hadar", level: 3, school: "Conjuration", castingTime: "Action", range: "150 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Hunter's Mark", level: 1, school: "Divination", castingTime: "Bonus Action", range: "90 ft", duration: "1 hour", components: "V", concentration: true, ritual: false },
    { name: "Hypnotic Pattern", level: 3, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "S,M", concentration: true, ritual: false },
    { name: "Ice Knife", level: 1, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "S,M", concentration: false, ritual: false },
    { name: "Ice Storm", level: 4, school: "Evocation", castingTime: "Action", range: "300 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Identify", level: 1, school: "Divination", castingTime: "1 minute", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: true },
    { name: "Illusory Script", level: 1, school: "Illusion", castingTime: "1 minute", range: "Touch", duration: "10 days", components: "S,M", concentration: false, ritual: true },
    { name: "Imprisonment", level: 9, school: "Abjuration", castingTime: "1 minute", range: "30 ft", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Incendiary Cloud", level: 8, school: "Conjuration", castingTime: "Action", range: "150 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Inflict Wounds", level: 1, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Insect Plague", level: 5, school: "Conjuration", castingTime: "Action", range: "300 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Invisibility", level: 2, school: "Illusion", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Jump", level: 1, school: "Transmutation", castingTime: "Bonus Action", range: "Touch", duration: "1 minute", components: "V,S,M", concentration: false, ritual: false },
    { name: "Knock", level: 2, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Legend Lore", level: 5, school: "Divination", castingTime: "10 minutes", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Leomund's Secret Chest", level: 4, school: "Conjuration", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Leomund's Tiny Hut", level: 3, school: "Evocation", castingTime: "1 minute", range: "Self", duration: "8 hours", components: "V,S,M", concentration: false, ritual: true },
    { name: "Lesser Restoration", level: 2, school: "Abjuration", castingTime: "Bonus Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Levitate", level: 2, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Light", level: 0, school: "Evocation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,M", concentration: false, ritual: false },
    { name: "Lightning Arrow", level: 3, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Lightning Bolt", level: 3, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Locate Animals or Plants", level: 2, school: "Divination", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: true },
    { name: "Locate Creature", level: 4, school: "Divination", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Locate Object", level: 2, school: "Divination", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Longstrider", level: 1, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mage Armor", level: 1, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mage Hand", level: 0, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S", concentration: false, ritual: false },
    { name: "Magic Circle", level: 3, school: "Abjuration", castingTime: "1 minute", range: "10 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Magic Jar", level: 6, school: "Necromancy", castingTime: "1 minute", range: "Self", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Magic Missile", level: 1, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Magic Mouth", level: 2, school: "Illusion", castingTime: "1 minute", range: "30 ft", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: true },
    { name: "Magic Weapon", level: 2, school: "Transmutation", castingTime: "Bonus Action", range: "Touch", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Major Image", level: 3, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Mass Cure Wounds", level: 5, school: "Abjuration", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Mass Heal", level: 9, school: "Abjuration", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Mass Healing Word", level: 3, school: "Abjuration", castingTime: "Bonus Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Mass Suggestion", level: 6, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "24 hours", components: "V,M", concentration: false, ritual: false },
    { name: "Maze", level: 8, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Meld into Stone", level: 3, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S", concentration: false, ritual: true },
    { name: "Melf's Acid Arrow", level: 2, school: "Evocation", castingTime: "Action", range: "90 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mending", level: 0, school: "Transmutation", castingTime: "1 minute", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Message", level: 0, school: "Transmutation", castingTime: "Action", range: "120 ft", duration: "1 round", components: "S,M", concentration: false, ritual: false },
    { name: "Meteor Swarm", level: 9, school: "Evocation", castingTime: "Action", range: "1 mile", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Mind Blank", level: 8, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "24 hours", components: "V,S", concentration: false, ritual: false },
    { name: "Mind Sliver", level: 0, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 round", components: "V", concentration: false, ritual: false },
    { name: "Mind Spike", level: 2, school: "Divination", castingTime: "Action", range: "120 ft", duration: "1 hour", components: "S", concentration: true, ritual: false },
    { name: "Minor Illusion", level: 0, school: "Illusion", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "S,M", concentration: false, ritual: false },
    { name: "Mirage Arcane", level: 7, school: "Illusion", castingTime: "10 minutes", range: "Sight", duration: "10 days", components: "V,S", concentration: false, ritual: false },
    { name: "Mirror Image", level: 2, school: "Illusion", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: false, ritual: false },
    { name: "Mislead", level: 5, school: "Illusion", castingTime: "Action", range: "Self", duration: "1 hour", components: "S", concentration: true, ritual: false },
    { name: "Misty Step", level: 2, school: "Conjuration", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Modify Memory", level: 5, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Moonbeam", level: 2, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Mordenkainen's Faithful Hound", level: 4, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mordenkainen's Magnificent Mansion", level: 7, school: "Conjuration", castingTime: "1 minute", range: "300 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mordenkainen's Private Sanctum", level: 4, school: "Abjuration", castingTime: "10 minutes", range: "120 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Mordenkainen's Sword", level: 7, school: "Evocation", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Move Earth", level: 6, school: "Transmutation", castingTime: "Action", range: "120 ft", duration: "2 hours", components: "V,S,M", concentration: true, ritual: false },
    { name: "Nondetection", level: 3, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Nystul's Magic Aura", level: 2, school: "Illusion", castingTime: "Action", range: "Touch", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Otiluke's Freezing Sphere", level: 6, school: "Evocation", castingTime: "Action", range: "300 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Otiluke's Resilient Sphere", level: 4, school: "Evocation", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Otto's Irresistible Dance", level: 6, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Pass without Trace", level: 2, school: "Abjuration", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Passwall", level: 5, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Phantasmal Force", level: 2, school: "Illusion", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Phantasmal Killer", level: 4, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Phantom Steed", level: 3, school: "Illusion", castingTime: "1 minute", range: "30 ft", duration: "1 hour", components: "V,S", concentration: false, ritual: true },
    { name: "Planar Ally", level: 6, school: "Conjuration", castingTime: "10 minutes", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Planar Binding", level: 5, school: "Abjuration", castingTime: "1 hour", range: "60 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Plane Shift", level: 7, school: "Conjuration", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Plant Growth", level: 3, school: "Transmutation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Poison Spray", level: 0, school: "Necromancy", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Polymorph", level: 4, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Power Word Heal", level: 9, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Power Word Kill", level: 9, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Power Word Stun", level: 8, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Prayer of Healing", level: 2, school: "Abjuration", castingTime: "10 minutes", range: "30 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Prestidigitation", level: 0, school: "Transmutation", castingTime: "Action", range: "10 ft", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Prismatic Spray", level: 7, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Prismatic Wall", level: 9, school: "Abjuration", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: false, ritual: false },
    { name: "Produce Flame", level: 0, school: "Conjuration", castingTime: "Bonus Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: false, ritual: false },
    { name: "Programmed Illusion", level: 6, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Project Image", level: 7, school: "Illusion", castingTime: "Action", range: "500 miles", duration: "1 day", components: "V,S,M", concentration: true, ritual: false },
    { name: "Protection from Energy", level: 3, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S", concentration: true, ritual: false },
    { name: "Protection from Evil and Good", level: 1, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Protection from Poison", level: 2, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S", concentration: false, ritual: false },
    { name: "Purify Food and Drink", level: 1, school: "Transmutation", castingTime: "Action", range: "10 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: true },
    { name: "Raise Dead", level: 5, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Rary's Telepathic Bond", level: 5, school: "Divination", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Ray of Enfeeblement", level: 2, school: "Necromancy", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Ray of Frost", level: 0, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Ray of Sickness", level: 1, school: "Necromancy", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Regenerate", level: 7, school: "Transmutation", castingTime: "1 minute", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Reincarnate", level: 5, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Remove Curse", level: 3, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Resistance", level: 0, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Resurrection", level: 7, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Reverse Gravity", level: 7, school: "Transmutation", castingTime: "Action", range: "100 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Revivify", level: 3, school: "Necromancy", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Rope Trick", level: 2, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Sacred Flame", level: 0, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Sanctuary", level: 1, school: "Abjuration", castingTime: "Bonus Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: false, ritual: false },
    { name: "Scorching Ray", level: 2, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Scrying", level: 5, school: "Divination", castingTime: "10 minutes", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Searing Smite", level: 1, school: "Evocation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: false, ritual: false },
    { name: "See Invisibility", level: 2, school: "Divination", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Seeming", level: 5, school: "Illusion", castingTime: "Action", range: "30 ft", duration: "8 hours", components: "V,S", concentration: false, ritual: false },
    { name: "Sending", level: 3, school: "Divination", castingTime: "Action", range: "Unlimited", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Sequester", level: 7, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Shapechange", level: 9, school: "Transmutation", castingTime: "Action", range: "Self", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Shatter", level: 2, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Shield", level: 1, school: "Abjuration", castingTime: "Reaction", range: "Self", duration: "1 round", components: "V,S", concentration: false, ritual: false },
    { name: "Shield of Faith", level: 1, school: "Abjuration", castingTime: "Bonus Action", range: "60 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Shillelagh", level: 0, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: false, ritual: false },
    { name: "Shining Smite", level: 2, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: true, ritual: false },
    { name: "Shocking Grasp", level: 0, school: "Evocation", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Silence", level: 2, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: true },
    { name: "Silent Image", level: 1, school: "Illusion", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Simulacrum", level: 7, school: "Illusion", castingTime: "12 hours", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Sleep", level: 1, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Sleet Storm", level: 3, school: "Conjuration", castingTime: "Action", range: "150 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Slow", level: 3, school: "Transmutation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Sorcerous Burst", level: 0, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Spare the Dying", level: 0, school: "Necromancy", castingTime: "Action", range: "15 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Speak with Animals", level: 1, school: "Divination", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: false, ritual: true },
    { name: "Speak with Dead", level: 3, school: "Necromancy", castingTime: "Action", range: "10 ft", duration: "10 minutes", components: "V,S,M", concentration: false, ritual: false },
    { name: "Speak with Plants", level: 3, school: "Transmutation", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S", concentration: false, ritual: false },
    { name: "Spider Climb", level: 2, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Spike Growth", level: 2, school: "Transmutation", castingTime: "Action", range: "150 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Spirit Guardians", level: 3, school: "Conjuration", castingTime: "Action", range: "Self", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Spiritual Weapon", level: 2, school: "Evocation", castingTime: "Bonus Action", range: "60 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Staggering Smite", level: 4, school: "Enchantment", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Starry Wisp", level: 0, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Steel Wind Strike", level: 5, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "S,M", concentration: false, ritual: false },
    { name: "Stinking Cloud", level: 3, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Stone Shape", level: 4, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Stoneskin", level: 4, school: "Transmutation", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Storm of Vengeance", level: 9, school: "Conjuration", castingTime: "Action", range: "1 mile", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Suggestion", level: 2, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "8 hours", components: "V,M", concentration: true, ritual: false },
    { name: "Summon Aberration", level: 4, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Beast", level: 2, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Celestial", level: 5, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Construct", level: 4, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Dragon", level: 5, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Elemental", level: 4, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Fey", level: 3, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Fiend", level: 6, school: "Conjuration", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Summon Undead", level: 3, school: "Necromancy", castingTime: "Action", range: "90 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Sunbeam", level: 6, school: "Evocation", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Sunburst", level: 8, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Swift Quiver", level: 5, school: "Transmutation", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Symbol", level: 7, school: "Abjuration", castingTime: "1 minute", range: "Touch", duration: "Dispelled", components: "V,S,M", concentration: false, ritual: false },
    { name: "Synaptic Static", level: 5, school: "Enchantment", castingTime: "Action", range: "120 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Tasha's Bubbling Cauldron", level: 6, school: "Conjuration", castingTime: "Action", range: "5 ft", duration: "10 minutes", components: "V,S,M", concentration: false, ritual: false },
    { name: "Tasha's Hideous Laughter", level: 1, school: "Enchantment", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Telekinesis", level: 5, school: "Transmutation", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: true, ritual: false },
    { name: "Teleport", level: 7, school: "Conjuration", castingTime: "Action", range: "10 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Teleportation Circle", level: 5, school: "Conjuration", castingTime: "1 minute", range: "10 ft", duration: "1 round", components: "V,M", concentration: false, ritual: false },
    { name: "Tenser's Floating Disk", level: 1, school: "Conjuration", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Thaumaturgy", level: 0, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 minute", components: "V", concentration: false, ritual: false },
    { name: "Thorn Whip", level: 0, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Thunderclap", level: 0, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "S", concentration: false, ritual: false },
    { name: "Thunderous Smite", level: 1, school: "Evocation", castingTime: "Bonus Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Thunderwave", level: 1, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Time Stop", level: 9, school: "Transmutation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Toll the Dead", level: 0, school: "Necromancy", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V,S", concentration: false, ritual: false },
    { name: "Tongues", level: 3, school: "Divination", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,M", concentration: false, ritual: false },
    { name: "Transport via Plants", level: 6, school: "Conjuration", castingTime: "Action", range: "10 ft", duration: "1 minute", components: "V,S", concentration: false, ritual: false },
    { name: "Tree Stride", level: 5, school: "Conjuration", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "True Polymorph", level: 9, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "True Resurrection", level: 9, school: "Necromancy", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "True Seeing", level: 6, school: "Divination", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "True Strike", level: 0, school: "Divination", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "S,M", concentration: false, ritual: false },
    { name: "Tsunami", level: 8, school: "Conjuration", castingTime: "1 minute", range: "1 mile", duration: "6 rounds", components: "V,S", concentration: true, ritual: false },
    { name: "Unseen Servant", level: 1, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Vampiric Touch", level: 3, school: "Necromancy", castingTime: "Action", range: "Self", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Vicious Mockery", level: 0, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Vitriolic Sphere", level: 4, school: "Evocation", castingTime: "Action", range: "150 ft", duration: "Instantaneous", components: "V,S,M", concentration: false, ritual: false },
    { name: "Wall of Fire", level: 4, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Wall of Force", level: 5, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Wall of Ice", level: 6, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Wall of Stone", level: 5, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Wall of Thorns", level: 6, school: "Conjuration", castingTime: "Action", range: "120 ft", duration: "10 minutes", components: "V,S,M", concentration: true, ritual: false },
    { name: "Warding Bond", level: 2, school: "Abjuration", castingTime: "Action", range: "Touch", duration: "1 hour", components: "V,S,M", concentration: false, ritual: false },
    { name: "Water Breathing", level: 3, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "24 hours", components: "V,S,M", concentration: false, ritual: true },
    { name: "Water Walk", level: 3, school: "Transmutation", castingTime: "Action", range: "30 ft", duration: "1 hour", components: "V,S,M", concentration: false, ritual: true },
    { name: "Web", level: 2, school: "Conjuration", castingTime: "Action", range: "60 ft", duration: "1 hour", components: "V,S,M", concentration: true, ritual: false },
    { name: "Weird", level: 9, school: "Illusion", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S", concentration: true, ritual: false },
    { name: "Wind Walk", level: 6, school: "Transmutation", castingTime: "1 minute", range: "30 ft", duration: "8 hours", components: "V,S,M", concentration: false, ritual: false },
    { name: "Wind Wall", level: 3, school: "Evocation", castingTime: "Action", range: "120 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Wish", level: 9, school: "Conjuration", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Witch Bolt", level: 1, school: "Evocation", castingTime: "Action", range: "60 ft", duration: "1 minute", components: "V,S,M", concentration: true, ritual: false },
    { name: "Word of Radiance", level: 0, school: "Evocation", castingTime: "Action", range: "Self", duration: "Instantaneous", components: "V,M", concentration: false, ritual: false },
    { name: "Word of Recall", level: 6, school: "Conjuration", castingTime: "Action", range: "5 ft", duration: "Instantaneous", components: "V", concentration: false, ritual: false },
    { name: "Wrathful Smite", level: 1, school: "Necromancy", castingTime: "Bonus Action", range: "Self", duration: "1 minute", components: "V", concentration: false, ritual: false },
    { name: "Zone of Truth", level: 2, school: "Enchantment", castingTime: "Action", range: "60 ft", duration: "10 minutes", components: "V,S", concentration: false, ritual: false }
];

// Get all spells
export function getAllSpells() {
    return SPELLS;
}

// Get cantrips only (level 0)
export function getCantrips() {
    return SPELLS.filter(s => s.level === 0);
}

// Get spells by level (1-9)
export function getSpellsByLevel(level) {
    return SPELLS.filter(s => s.level === level);
}

// Get non-cantrip spells (level 1+)
export function getLeveledSpells() {
    return SPELLS.filter(s => s.level > 0);
}

// Search spells by name (case-insensitive partial match)
export function searchSpells(query, options = {}) {
    const { cantripsOnly = false, leveledOnly = false, maxLevel = 9, minLevel = 0 } = options;
    
    let results = SPELLS;
    
    // Filter by level range
    results = results.filter(s => s.level >= minLevel && s.level <= maxLevel);
    
    // Filter cantrips/leveled
    if (cantripsOnly) {
        results = results.filter(s => s.level === 0);
    } else if (leveledOnly) {
        results = results.filter(s => s.level > 0);
    }
    
    // Filter by name if query provided
    if (query && query.trim()) {
        const lowerQuery = query.toLowerCase().trim();
        results = results.filter(s => s.name.toLowerCase().includes(lowerQuery));
    }
    
    return results;
}

// Get spell by exact name
export function getSpell(name) {
    return SPELLS.find(s => s.name.toLowerCase() === name.toLowerCase());
}

// Format spell level for display
export function formatSpellLevel(level) {
    if (level === 0) return 'Cantrip';
    if (level === 1) return '1st';
    if (level === 2) return '2nd';
    if (level === 3) return '3rd';
    return `${level}th`;
}

// Get aidedd.org URL for a spell
export function getSpellUrl(name) {
    const urlName = name.toLowerCase()
        .replace(/'/g, '-')
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '');
    return `https://www.aidedd.org/spell/${urlName}`;
}

export default {
    getAllSpells,
    getCantrips,
    getSpellsByLevel,
    getLeveledSpells,
    searchSpells,
    getSpell,
    formatSpellLevel,
    getSpellUrl
};
